
import React, { useState, useEffect } from 'react';
import { X, Database, Terminal, AlertTriangle, Wand2, Loader2, CheckCircle, Play } from 'lucide-react';
import { CopyToClipboard } from './CopyToClipboard';
import { fixSqlScript } from '../services/geminiService';

interface DatabaseSetupModalProps {
  isOpen: boolean;
  onClose: () => void;
}

// STEP 1: TABLES, SETTINGS & CLEANUP (Schema V9.0.29 - ADMIN SECURITY)
const DEFAULT_SQL_1 = `BEGIN;
-- 1. CLEANUP OLD FUNCTIONS
DROP FUNCTION IF EXISTS public.process_payout(bigint,text,text);
DROP FUNCTION IF EXISTS public.process_payout(bigint,public.payout_status_enum,text);
DROP FUNCTION IF EXISTS public.admin_get_licenses_paginated(integer,integer,text,text,text,text);
DROP FUNCTION IF EXISTS public.admin_get_licenses_paginated(integer,integer,text,text,text,text,text);
DROP FUNCTION IF EXISTS public.admin_get_dashboard_metrics();
DROP FUNCTION IF EXISTS public.admin_update_user(bigint,text,text,text,text,text,integer,text,numeric,text,text,text,numeric,timestamptz,text,text);
-- Specific cleanup for the error encountered
DROP FUNCTION IF EXISTS public.admin_update_user(bigint,text,text,text,text,text,integer,text,numeric,text,text,text,numeric,timestamptz,text,text,numeric,numeric,text);
DROP FUNCTION IF EXISTS public.admin_bulk_action(integer[],text);
DROP FUNCTION IF EXISTS public.admin_bulk_action(bigint[],text); 
DROP FUNCTION IF EXISTS public.request_payout(text,numeric,text);
DROP TRIGGER IF EXISTS on_license_status_change ON public.licenses;
DROP FUNCTION IF EXISTS public.process_referral_commission();
DROP FUNCTION IF EXISTS public.verify_admin_password(text);
-- New cleanup
DROP FUNCTION IF EXISTS public.admin_get_global_referrals(integer,integer,text);
DROP FUNCTION IF EXISTS public.admin_get_global_ledger(integer,integer,text,text);

-- 2. CREATE TABLES
CREATE TABLE IF NOT EXISTS public.licenses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz DEFAULT now() NOT NULL,
    license_key text UNIQUE NOT NULL,
    user_name text,
    user_email text,
    phone_number text,
    plan_type text DEFAULT 'Starter',
    credits integer DEFAULT 0,
    status text DEFAULT 'pending',
    subscription_end_date timestamptz,
    affiliate_code text UNIQUE,
    referred_by_code text,
    affiliate_balance numeric DEFAULT 0,
    total_earnings numeric DEFAULT 0,
    affiliate_tier text DEFAULT 'Agent',
    successful_referrals integer DEFAULT 0,
    custom_commission_rate numeric,
    bank_name text,
    bank_details text,
    bank_holder text,
    updated_at timestamptz DEFAULT now(),
    snapshot_discount numeric DEFAULT 0,
    snapshot_commission_rate numeric DEFAULT 0,
    commission_processed boolean DEFAULT false,
    admin_notes text
);

CREATE TABLE IF NOT EXISTS public.affiliate_logs (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,created_at timestamptz DEFAULT now() NOT NULL,license_key text NOT NULL,amount numeric NOT NULL,type text NOT NULL,description text,from_user text,commission_rate numeric,source_amount numeric);
CREATE TABLE IF NOT EXISTS public.payout_requests (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,created_at timestamptz DEFAULT now() NOT NULL,license_key text NOT NULL,amount numeric NOT NULL,status text DEFAULT 'pending',bank_details text,admin_note text,processed_at timestamptz);
CREATE TABLE IF NOT EXISTS public.broadcasts (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,created_at timestamptz DEFAULT now() NOT NULL,title text NOT NULL,message text NOT NULL,type text DEFAULT 'info',is_active boolean DEFAULT true,expires_at timestamptz);
CREATE TABLE IF NOT EXISTS public.audit_trail (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,created_at timestamptz DEFAULT now() NOT NULL,admin_actor text DEFAULT 'System',action text NOT NULL,target_license_key text,details jsonb);
CREATE TABLE IF NOT EXISTS public.system_settings (key text PRIMARY KEY,value text,description text);
CREATE TABLE IF NOT EXISTS public.coupons (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,code text UNIQUE NOT NULL,discount_type text DEFAULT 'percentage',discount_value numeric NOT NULL,is_active boolean DEFAULT true,usage_limit integer DEFAULT 100,used_count integer DEFAULT 0,created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.packages (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name text NOT NULL,price numeric NOT NULL,credits int NOT NULL,features jsonb DEFAULT '[]'::jsonb,is_active boolean DEFAULT true,is_popular boolean DEFAULT false,ref_code text,period text DEFAULT '/ month',old_price numeric,credit_label text,color_theme text DEFAULT 'blue',created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.feedback_logs (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at timestamptz DEFAULT now(), license_key text, rating text, content_snippet text);

-- 3. SEED INITIAL DATA
INSERT INTO public.packages (name,price,credits,features,is_popular,ref_code,old_price,credit_label,color_theme) SELECT 'Basic Plan',69,200,'["Auto-Fill & Manual Input","Access to Neural Engine V4","Normal Speed","Email Support","GenPro Studio LOCKED"]'::jsonb,false,'BASIC-M',null,'200 Credits / Month','blue' WHERE NOT EXISTS (SELECT 1 FROM public.packages WHERE name='Basic Plan');
INSERT INTO public.packages (name,price,credits,features,is_popular,ref_code,old_price,credit_label,color_theme) SELECT 'TAAP PRO',199,600,'["Massive 600 Credits","GenPro Studio (Image Gen)","Viral Trend Search","Priority Queue"]'::jsonb,true,'PRO-M',299,'600 Credits / Month','orange' WHERE NOT EXISTS (SELECT 1 FROM public.packages WHERE name='TAAP PRO');

INSERT INTO public.system_settings (key,value,description) VALUES 
('admin_password', 'admin123', 'Secure Admin Access Password'),
('cost_per_generation','1','Cost per text'),
('cost_per_autofill','1','Cost per autofill'),
('cost_per_image_generation','2','Cost per Imagen'),
('cost_per_video_generation','10','Cost per Veo'),
('cost_per_trend_search','2','Cost per Viral Trend Search'),
('referral_discount_percent','50','Discount for new users via referral (Updated)'),
('affiliate_commission_agent','20','Agent Commission % (Updated)'),
('affiliate_commission_super','25','Super Agent Commission % (Updated)'),
('affiliate_commission_partner','30','Partner Commission % (Updated)'),
('tier_req_super_agent','50','Referrals required for Super Agent (Updated)'),
('tier_req_partner','100','Referrals required for Partner (Updated)'),
('admin_whatsapp','60176162761','Admin Contact Number'),
('payment_qr_url', 'https://lh3.googleusercontent.com/d/1AlmtkkZgELIA_zul3vGsWQ36zJ73X3wI', 'DuitNow QR Image URL') 
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

-- 4. DB MIGRATION: PAYOUT STATUS FIX & CONSTRAINT REBUILD
DO $$ 
DECLARE
    r RECORD;
BEGIN 
    -- MIGRATE LEGACY 'declined' STATUS TO 'rejected'
    UPDATE public.payout_requests SET status = 'rejected' WHERE status = 'declined';

    -- DYNAMICALLY FIND AND DROP ALL CHECK CONSTRAINTS ON PAYOUT_REQUESTS
    FOR r IN (
        SELECT con.conname
        FROM pg_catalog.pg_constraint con
        INNER JOIN pg_catalog.pg_class rel ON rel.oid = con.conrelid
        INNER JOIN pg_catalog.pg_namespace nsp ON nsp.oid = connamespace
        WHERE nsp.nspname = 'public'
          AND rel.relname = 'payout_requests'
          AND con.contype = 'c' -- Check constraint
    ) LOOP
        EXECUTE 'ALTER TABLE public.payout_requests DROP CONSTRAINT IF EXISTS ' || quote_ident(r.conname);
    END LOOP;

    -- Force column to TEXT to remove any Enum dependencies
    ALTER TABLE public.payout_requests ALTER COLUMN status TYPE text;
    ALTER TABLE public.payout_requests ALTER COLUMN status SET DEFAULT 'pending';
    
    -- ADD A NEW, CORRECT CONSTRAINT to prevent future invalid values
    ALTER TABLE public.payout_requests DROP CONSTRAINT IF EXISTS payout_status_valid_values;
    ALTER TABLE public.payout_requests ADD CONSTRAINT payout_status_valid_values CHECK (status IN ('pending', 'approved', 'rejected'));

    -- Ensure other columns exist (idempotent checks)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='licenses' AND column_name='commission_processed') THEN 
        ALTER TABLE public.licenses ADD COLUMN commission_processed boolean DEFAULT false; 
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='licenses' AND column_name='snapshot_discount') THEN 
        ALTER TABLE public.licenses ADD COLUMN snapshot_discount numeric DEFAULT 0; 
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='licenses' AND column_name='snapshot_commission_rate') THEN 
        ALTER TABLE public.licenses ADD COLUMN snapshot_commission_rate numeric DEFAULT 0; 
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='licenses' AND column_name='admin_notes') THEN 
        ALTER TABLE public.licenses ADD COLUMN admin_notes text; 
    END IF;
    
    -- Fix: Ensure coupons usage_limit exists
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='coupons' AND column_name='usage_limit') THEN
        ALTER TABLE public.coupons ADD COLUMN usage_limit integer DEFAULT 100;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='coupons' AND column_name='used_count') THEN
        ALTER TABLE public.coupons ADD COLUMN used_count integer DEFAULT 0;
    END IF;
END $$;

-- 5. HOTFIX: GRANT ACCESS TO SETTINGS IMMEDIATELY
GRANT SELECT ON public.system_settings TO anon;
GRANT SELECT ON public.packages TO anon;

COMMIT;`;

// STEP 2: CORE TRIGGERS (Schema V9.0.30 - SECURITY FIXES)
const DEFAULT_SQL_2 = `BEGIN;
-- LOGGING HELPER
CREATE OR REPLACE FUNCTION public.log_admin_action(p_action text,p_target text,p_details jsonb) RETURNS void LANGUAGE plpgsql AS $$ BEGIN INSERT INTO public.audit_trail (action,target_license_key,details) VALUES (p_action,p_target,p_details); END; $$;

-- AFFILIATE COMMISSION TRIGGER
CREATE OR REPLACE FUNCTION public.process_referral_commission() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$ 
DECLARE 
  v_rkey text; 
  v_tier text; 
  v_count int; 
  v_rate numeric; 
  v_custom numeric; 
  v_price numeric; 
  v_comm numeric; 
  v_discount_used numeric;
  v_should_process boolean := false;
  v_locked_rate numeric;
  
  -- Dynamic Settings Variables
  v_req_super int;
  v_req_partner int;
  v_rate_agent numeric;
  v_rate_super numeric;
  v_rate_partner numeric;
BEGIN 
  IF (TG_OP = 'INSERT') THEN
      IF NEW.status = 'active' THEN v_should_process := true; END IF;
  ELSIF (TG_OP = 'UPDATE') THEN
      IF NEW.status = 'active' AND OLD.status != 'active' THEN v_should_process := true; END IF;
  END IF;

  IF v_should_process AND NEW.referred_by_code IS NOT NULL AND (NEW.commission_processed IS NULL OR NEW.commission_processed = false) THEN 
    BEGIN
        SELECT license_key,affiliate_tier,successful_referrals,custom_commission_rate INTO v_rkey,v_tier,v_count,v_custom FROM public.licenses WHERE affiliate_code=NEW.referred_by_code; 
        
        -- Load Dynamic Settings
        SELECT value::int INTO v_req_super FROM public.system_settings WHERE key='tier_req_super_agent';
        SELECT value::int INTO v_req_partner FROM public.system_settings WHERE key='tier_req_partner';
        SELECT value::numeric INTO v_rate_agent FROM public.system_settings WHERE key='affiliate_commission_agent';
        SELECT value::numeric INTO v_rate_super FROM public.system_settings WHERE key='affiliate_commission_super';
        SELECT value::numeric INTO v_rate_partner FROM public.system_settings WHERE key='affiliate_commission_partner';
        
        -- Default Fallbacks
        v_req_super := COALESCE(v_req_super, 50);
        v_req_partner := COALESCE(v_req_partner, 100);
        v_rate_agent := COALESCE(v_rate_agent, 20.0);
        v_rate_super := COALESCE(v_rate_super, 25.0);
        v_rate_partner := COALESCE(v_rate_partner, 30.0);

        IF v_rkey IS NOT NULL AND v_rkey!=NEW.license_key THEN 
          -- DYNAMIC PRICE LOOKUP
          SELECT price INTO v_price FROM public.packages WHERE name = NEW.plan_type;
          v_price := COALESCE(v_price, 69.00);

          v_discount_used := COALESCE(NEW.snapshot_discount, 0);
          IF v_discount_used > 0 THEN v_price := v_price - (v_price * (v_discount_used / 100.0)); END IF;
          
          -- Rate Logic
          v_locked_rate := COALESCE(NEW.snapshot_commission_rate, 0);
          IF v_locked_rate > 0 THEN v_rate := v_locked_rate; 
          ELSE
             IF v_custom IS NOT NULL THEN v_rate:=v_custom; 
             ELSIF v_tier='Partner' THEN v_rate:=v_rate_partner; 
             ELSIF v_tier='Super Agent' THEN v_rate:=v_rate_super; 
             ELSE v_rate:=v_rate_agent; 
             END IF; 
          END IF;
          
          v_comm := v_price * (v_rate / 100.0); 
          INSERT INTO public.affiliate_logs (license_key,amount,type,description,from_user,commission_rate,source_amount) 
          VALUES (v_rkey,v_comm,'commission','Comm: '||NEW.user_name,NEW.user_name,v_rate,v_price); 
          
          UPDATE public.licenses SET affiliate_balance=affiliate_balance+v_comm,total_earnings=total_earnings+v_comm,successful_referrals=successful_referrals+1 WHERE license_key=v_rkey; 
          
          -- Tier Upgrade Logic
          v_count:=v_count+1; 
          IF v_tier='Agent' AND v_count >= v_req_super THEN 
              UPDATE public.licenses SET affiliate_tier='Super Agent' WHERE license_key=v_rkey; 
          ELSIF v_tier='Super Agent' AND v_count >= v_req_partner THEN 
              UPDATE public.licenses SET affiliate_tier='Partner' WHERE license_key=v_rkey; 
          END IF;
        END IF; 
        NEW.commission_processed := true;
    EXCEPTION WHEN OTHERS THEN
        INSERT INTO public.audit_trail (action, target_license_key, details) VALUES ('COMMISSION_ERROR', NEW.license_key, jsonb_build_object('error', SQLERRM));
    END;
  END IF; 
  RETURN NEW; 
END; 
$$;

DROP TRIGGER IF EXISTS on_license_status_change ON public.licenses;
CREATE TRIGGER on_license_status_change BEFORE INSERT OR UPDATE ON public.licenses FOR EACH ROW EXECUTE FUNCTION public.process_referral_commission();

-- GET REFERRALS
DROP FUNCTION IF EXISTS public.get_user_referrals(text);
CREATE OR REPLACE FUNCTION public.get_user_referrals(p_license_key text) RETURNS TABLE (user_name text, affiliate_code text, plan_type text, joined_at timestamptz, status text, commission_earned numeric, snapshot_discount numeric, snapshot_commission_rate numeric, commission_processed boolean) LANGUAGE plpgsql SECURITY DEFINER AS $$ 
DECLARE v_code text; 
BEGIN 
  SELECT l.affiliate_code INTO v_code FROM public.licenses l WHERE l.license_key=p_license_key; 
  IF v_code IS NULL THEN RETURN; END IF; 
  RETURN QUERY 
  SELECT l.user_name, l.affiliate_code, l.plan_type, l.created_at, l.status,COALESCE((SELECT SUM(amount) FROM public.affiliate_logs al WHERE al.from_user=l.user_name AND al.license_key=p_license_key AND al.type='commission'),0)::numeric,COALESCE(l.snapshot_discount, 0)::numeric,COALESCE(l.snapshot_commission_rate, 0)::numeric,COALESCE(l.commission_processed, false)
  FROM public.licenses l WHERE l.referred_by_code=v_code ORDER BY l.created_at DESC; 
END; 
$$;

-- SECURE NEW REGISTRATION (Ignores client snapshot)
CREATE OR REPLACE FUNCTION public.register_new_user(
    p_license_key text,
    p_name text,
    p_email text,
    p_phone text,
    p_plan text,
    p_referral_code text,
    p_snapshot_discount numeric -- Ignored, calculated internally
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER AS $$ 
DECLARE 
  v_new_id bigint;
  v_ac text; 
  v_upline_rate numeric := 0;
  v_upline_tier text;
  v_upline_custom numeric;
  v_rate_agent numeric;
  v_rate_super numeric;
  v_rate_partner numeric;
  v_initial_credits int;
  v_verified_discount numeric := 0;
BEGIN 
  PERFORM 1 FROM public.licenses WHERE user_email=p_email; 
  IF FOUND THEN RETURN jsonb_build_object('status','error','message','Email already registered'); END IF; 
  
  -- Load Dynamic Rates
  SELECT value::numeric INTO v_rate_agent FROM public.system_settings WHERE key='affiliate_commission_agent';
  SELECT value::numeric INTO v_rate_super FROM public.system_settings WHERE key='affiliate_commission_super';
  SELECT value::numeric INTO v_rate_partner FROM public.system_settings WHERE key='affiliate_commission_partner';
  
  v_rate_agent := COALESCE(v_rate_agent, 20.0);
  v_rate_super := COALESCE(v_rate_super, 25.0);
  v_rate_partner := COALESCE(v_rate_partner, 30.0);

  -- Get initial credits from package
  SELECT credits INTO v_initial_credits FROM public.packages WHERE name = p_plan;
  v_initial_credits := COALESCE(v_initial_credits, 200);

  -- Secure Snapshot Logic: Verify Code & Discount Server Side
  IF p_referral_code IS NOT NULL AND p_referral_code != '' THEN
      SELECT affiliate_tier, custom_commission_rate INTO v_upline_tier, v_upline_custom 
      FROM public.licenses WHERE affiliate_code = p_referral_code;
      
      IF FOUND THEN
          -- Valid Code: Apply System Discount
          SELECT value::numeric INTO v_verified_discount FROM public.system_settings WHERE key='referral_discount_percent';
          v_verified_discount := COALESCE(v_verified_discount, 0);

          -- Determine Upline Commission Rate
          if v_upline_custom IS NOT NULL THEN v_upline_rate := v_upline_custom;
          ELSIF v_upline_tier = 'Partner' THEN v_upline_rate := v_rate_partner;
          ELSIF v_upline_tier = 'Super Agent' THEN v_upline_rate := v_rate_super;
          ELSE v_upline_rate := v_rate_agent;
          END IF;
      END IF;
  END IF;

  INSERT INTO public.licenses (
      license_key, user_name, user_email, phone_number, plan_type, credits, status, 
      affiliate_code, referred_by_code, snapshot_discount, snapshot_commission_rate, subscription_end_date
  ) VALUES (
      p_license_key, p_name, p_email, p_phone, p_plan, v_initial_credits, 'pending', 
      NULL, p_referral_code, v_verified_discount, v_upline_rate, NULL
  ) RETURNING id INTO v_new_id; 
  
  v_ac := 'TAAP-G' || LPAD(v_new_id::text, 4, '0'); 
  UPDATE public.licenses SET affiliate_code = v_ac WHERE id = v_new_id;
  
  PERFORM public.log_admin_action('CREATE_USER', p_license_key, jsonb_build_object('email', p_email)); 
  RETURN jsonb_build_object('status','success','license_key', p_license_key); 
  EXCEPTION WHEN OTHERS THEN RETURN jsonb_build_object('status','error','message',SQLERRM);
END; 
$$;

COMMIT;`;

// STEP 3: ADMIN LOGIC & DASHBOARD FUNCTIONS (MISSING PIECE)
const DEFAULT_SQL_3 = `BEGIN;

-- 1. ADMIN AUTH
CREATE OR REPLACE FUNCTION public.verify_admin_password(p_password text) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER AS $$ 
DECLARE v_stored text; 
BEGIN 
  SELECT value INTO v_stored FROM public.system_settings WHERE key='admin_password'; 
  RETURN v_stored = p_password; 
END; 
$$;

-- 2. DASHBOARD METRICS
CREATE OR REPLACE FUNCTION public.admin_get_dashboard_metrics() RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER AS $$ 
DECLARE 
  v_total_users int; 
  v_active_users int; 
  v_total_aff int; 
  v_total_earned numeric; 
  v_pending_req_count int; 
  v_pending_req_amount numeric; 
  v_total_credits_used int; -- Placeholder for now
BEGIN 
  SELECT COUNT(*), COUNT(*) FILTER (WHERE status='active') INTO v_total_users, v_active_users FROM public.licenses; 
  SELECT COUNT(*) FILTER (WHERE successful_referrals > 0), COALESCE(SUM(total_earnings),0) INTO v_total_aff, v_total_earned FROM public.licenses; 
  SELECT COUNT(*), COALESCE(SUM(amount),0) INTO v_pending_req_count, v_pending_req_amount FROM public.payout_requests WHERE status='pending';
  
  RETURN jsonb_build_object(
    'total_licenses', v_total_users,
    'active_licenses', v_active_users,
    'total_affiliates', v_total_aff,
    'affiliate_conversion_rate', CASE WHEN v_total_users > 0 THEN ROUND((v_total_aff::numeric / v_total_users::numeric) * 100, 1) ELSE 0 END,
    'total_lifetime_affiliate_earnings', v_total_earned,
    'pending_payouts_count', v_pending_req_count,
    'pending_payouts_amount', v_pending_req_amount,
    'total_credits_consumed', 125000 -- Mock value for now until credit logs are fully implemented
  );
END; 
$$;

-- 3. USER MANAGEMENT (PAGINATED)
CREATE OR REPLACE FUNCTION public.admin_get_licenses_paginated(
    p_page integer,
    p_limit integer,
    p_search_term text,
    p_sort_by text DEFAULT 'created_at',
    p_sort_dir text DEFAULT 'desc',
    p_ref_filter text DEFAULT NULL,
    p_status text DEFAULT NULL
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_offset integer;
    v_total integer;
    v_data jsonb;
BEGIN
    v_offset := (p_page - 1) * p_limit;

    -- Count Total
    SELECT COUNT(*) INTO v_total
    FROM public.licenses
    WHERE 
        (p_search_term IS NULL OR 
         license_key ILIKE '%' || p_search_term || '%' OR 
         user_name ILIKE '%' || p_search_term || '%' OR 
         user_email ILIKE '%' || p_search_term || '%')
    AND
        (p_status IS NULL OR status = p_status);

    -- Fetch Data
    SELECT jsonb_agg(t) INTO v_data
    FROM (
        SELECT * FROM public.licenses
        WHERE 
            (p_search_term IS NULL OR 
             license_key ILIKE '%' || p_search_term || '%' OR 
             user_name ILIKE '%' || p_search_term || '%' OR 
             user_email ILIKE '%' || p_search_term || '%')
        AND
            (p_status IS NULL OR status = p_status)
        ORDER BY 
            CASE WHEN p_sort_dir = 'asc' THEN created_at END ASC,
            CASE WHEN p_sort_dir = 'desc' THEN created_at END DESC
        LIMIT p_limit OFFSET v_offset
    ) t;

    RETURN jsonb_build_object(
        'data', COALESCE(v_data, '[]'::jsonb),
        'total', v_total,
        'page', p_page,
        'limit', p_limit
    );
END;
$$;

-- 4. UPDATE USER
-- DROP old conflicting signatures
DROP FUNCTION IF EXISTS public.admin_update_user(bigint,text,text,text,text,text,integer,text,numeric,text,text,text,numeric,timestamptz,text,text,numeric,numeric,text);

CREATE OR REPLACE FUNCTION public.admin_update_user(
    p_id bigint,
    p_name text,
    p_email text,
    p_phone text,
    p_plan text,
    p_status text,
    p_credits integer,
    p_tier text,
    p_custom_rate numeric,
    p_bank_name text,
    p_bank_acc text,
    p_bank_holder text,
    p_balance numeric,
    p_expiry timestamptz,
    p_affiliate_code text,
    p_referred_by_code text,
    p_snapshot_discount numeric DEFAULT 0,
    p_snapshot_commission_rate numeric DEFAULT 0,
    p_admin_notes text DEFAULT NULL,
    p_license_key text DEFAULT NULL -- NEW: Allow updating license key
) RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    UPDATE public.licenses SET
        user_name = p_name,
        user_email = p_email,
        phone_number = p_phone,
        plan_type = p_plan,
        status = p_status,
        credits = p_credits,
        affiliate_tier = p_tier,
        custom_commission_rate = p_custom_rate,
        bank_name = p_bank_name,
        bank_details = p_bank_acc,
        bank_holder = p_bank_holder,
        affiliate_balance = p_balance,
        subscription_end_date = p_expiry,
        affiliate_code = p_affiliate_code,
        referred_by_code = p_referred_by_code,
        snapshot_discount = p_snapshot_discount,
        snapshot_commission_rate = p_snapshot_commission_rate,
        admin_notes = p_admin_notes,
        license_key = COALESCE(p_license_key, license_key), -- Update License Key if provided
        updated_at = now()
    WHERE id = p_id;
    
    PERFORM public.log_admin_action('UPDATE_USER', (SELECT license_key FROM public.licenses WHERE id = p_id), jsonb_build_object('id', p_id));
END;
$$;

-- 5. BULK ACTIONS
CREATE OR REPLACE FUNCTION public.admin_bulk_action(p_ids bigint[], p_action text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE v_count int;
BEGIN
    IF p_action = 'approve' THEN
        UPDATE public.licenses SET status = 'active', subscription_end_date = now() + interval '30 days' WHERE id = ANY(p_ids);
    ELSIF p_action = 'suspend' THEN
        UPDATE public.licenses SET status = 'suspended' WHERE id = ANY(p_ids);
    ELSIF p_action = 'delete' THEN
        DELETE FROM public.licenses WHERE id = ANY(p_ids);
    END IF;
    
    GET DIAGNOSTICS v_count = ROW_COUNT;
    PERFORM public.log_admin_action('BULK_' || UPPER(p_action), 'BATCH', jsonb_build_object('count', v_count, 'ids', p_ids));
    RETURN jsonb_build_object('status', 'success', 'count', v_count);
END;
$$;

-- 6. PROCESS PAYOUT
CREATE OR REPLACE FUNCTION public.process_payout(p_payout_id bigint, p_status text, p_admin_note text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_req RECORD;
BEGIN
    SELECT * INTO v_req FROM public.payout_requests WHERE id = p_payout_id;
    IF NOT FOUND THEN RETURN jsonb_build_object('status','error','message','Request not found'); END IF;

    UPDATE public.payout_requests SET status = p_status, admin_note = p_admin_note, processed_at = now() WHERE id = p_payout_id;

    IF p_status = 'rejected' THEN
        UPDATE public.licenses SET affiliate_balance = affiliate_balance + v_req.amount WHERE license_key = v_req.license_key;
        INSERT INTO public.affiliate_logs (license_key, amount, type, description) VALUES (v_req.license_key, v_req.amount, 'refund', 'Payout Rejected: ' || p_admin_note);
    ELSIF p_status = 'approved' THEN
        INSERT INTO public.affiliate_logs (license_key, amount, type, description) VALUES (v_req.license_key, -v_req.amount, 'withdrawal', 'Payout Approved');
    END IF;

    PERFORM public.log_admin_action('PROCESS_PAYOUT', v_req.license_key, jsonb_build_object('id', p_payout_id, 'status', p_status));
    RETURN jsonb_build_object('status', 'success');
END;
$$;

-- 7. SETTINGS & PACKAGES
CREATE OR REPLACE FUNCTION public.admin_update_setting(p_key text, p_value text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    INSERT INTO public.system_settings (key, value) VALUES (p_key, p_value)
    ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
    PERFORM public.log_admin_action('UPDATE_SETTING', 'SYSTEM', jsonb_build_object('key', p_key, 'val', p_value));
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_update_package(p_id bigint, p_updates jsonb) RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    UPDATE public.packages SET
        name = COALESCE((p_updates->>'name'), name),
        price = COALESCE((p_updates->>'price')::numeric, price),
        credits = COALESCE((p_updates->>'credits')::int, credits),
        is_active = COALESCE((p_updates->>'is_active')::boolean, is_active),
        is_popular = COALESCE((p_updates->>'is_popular')::boolean, is_popular),
        features = COALESCE((p_updates->>'features')::jsonb, features),
        ref_code = COALESCE((p_updates->>'ref_code'), ref_code),
        period = COALESCE((p_updates->>'period'), period),
        color_theme = COALESCE((p_updates->>'color_theme'), color_theme),
        old_price = COALESCE((p_updates->>'old_price')::numeric, old_price)
    WHERE id = p_id;
END;
$$;

-- 8. LEADERBOARD (Updated to return affiliate_code for anonymous display)
DROP FUNCTION IF EXISTS public.admin_get_affiliate_leaderboard();
CREATE OR REPLACE FUNCTION public.admin_get_affiliate_leaderboard() RETURNS TABLE (license_key text, user_name text, total_earnings numeric, referral_count integer, affiliate_tier text, affiliate_code text) LANGUAGE sql SECURITY DEFINER AS $$
    SELECT license_key, user_name, total_earnings, successful_referrals, affiliate_tier, affiliate_code
    FROM public.licenses
    WHERE total_earnings > 0
    ORDER BY total_earnings DESC
    LIMIT 50;
$$;

-- 9. AUDIT TRAIL
CREATE OR REPLACE FUNCTION public.admin_get_audit_trail(p_page int, p_limit int, p_search_action text DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE v_data jsonb;
BEGIN
    SELECT jsonb_agg(t) INTO v_data FROM (
        SELECT * FROM public.audit_trail 
        WHERE (p_search_action IS NULL OR action ILIKE '%' || p_search_action || '%')
        ORDER BY created_at DESC 
        LIMIT p_limit OFFSET (p_page - 1) * p_limit
    ) t;
    RETURN jsonb_build_object('data', COALESCE(v_data, '[]'::jsonb));
END;
$$;

-- 10. CREDIT MANAGEMENT
CREATE OR REPLACE FUNCTION public.deduct_credits(p_license_key text, p_amount int, p_type text DEFAULT 'generation') RETURNS integer LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE v_current int;
BEGIN
    SELECT credits INTO v_current FROM public.licenses WHERE license_key = p_license_key;
    IF v_current IS NULL THEN RAISE EXCEPTION 'License not found'; END IF;
    IF v_current < p_amount THEN RAISE EXCEPTION 'Insufficient credits'; END IF;
    
    UPDATE public.licenses SET credits = credits - p_amount, last_used_at = now() WHERE license_key = p_license_key;
    
    -- Log credit usage (Optional: Create credit_logs table for detailed tracking)
    -- INSERT INTO credit_logs ...
    
    RETURN v_current - p_amount;
END;
$$;

-- 11. PAYOUT REQUEST
CREATE OR REPLACE FUNCTION public.request_payout(p_license_key text, p_amount numeric, p_bank_details text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE v_bal numeric;
BEGIN
    SELECT affiliate_balance INTO v_bal FROM public.licenses WHERE license_key = p_license_key;
    IF v_bal < p_amount THEN RETURN jsonb_build_object('status','error','message','Insufficient balance'); END IF;
    
    UPDATE public.licenses SET affiliate_balance = affiliate_balance - p_amount WHERE license_key = p_license_key;
    INSERT INTO public.payout_requests (license_key, amount, status, bank_details) VALUES (p_license_key, p_amount, 'pending', p_bank_details);
    INSERT INTO public.affiliate_logs (license_key, amount, type, description) VALUES (p_license_key, -p_amount, 'withdrawal', 'Payout Requested');
    
    RETURN jsonb_build_object('status','success');
END;
$$;

COMMIT;`;

// STEP 4: ADVANCED FEATURES (Schema V9.0.31 - Coupons, Monitor & Helpers)
const DEFAULT_SQL_4 = `BEGIN;

-- 1. COUPON VERIFICATION
CREATE OR REPLACE FUNCTION public.verify_coupon(p_code text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_coupon RECORD;
BEGIN
    SELECT * INTO v_coupon FROM public.coupons WHERE code = UPPER(p_code) AND is_active = true;
    
    IF NOT FOUND THEN
        RETURN jsonb_build_object('status', 'error', 'message', 'Invalid or inactive coupon');
    END IF;

    IF v_coupon.usage_limit > 0 AND v_coupon.used_count >= v_coupon.usage_limit THEN
        RETURN jsonb_build_object('status', 'error', 'message', 'Coupon usage limit reached');
    END IF;

    RETURN jsonb_build_object(
        'status', 'success',
        'data', jsonb_build_object(
            'code', v_coupon.code,
            'type', v_coupon.discount_type,
            'value', v_coupon.discount_value
        )
    );
END;
$$;

-- 2. ADMIN MANAGE COUPON
CREATE OR REPLACE FUNCTION public.admin_manage_coupon(
    p_action text,
    p_id bigint,
    p_code text,
    p_value numeric,
    p_type text,
    p_limit integer
) RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    IF p_action = 'create' THEN
        INSERT INTO public.coupons (code, discount_value, discount_type, usage_limit, is_active)
        VALUES (p_code, p_value, p_type, p_limit, true);
    ELSIF p_action = 'delete' THEN
        DELETE FROM public.coupons WHERE id = p_id;
    END IF;
END;
$$;

-- 3. GLOBAL REFERRAL MONITOR
CREATE OR REPLACE FUNCTION public.admin_get_global_referrals(
    p_page integer,
    p_limit integer,
    p_search text
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_offset integer;
    v_total integer;
    v_data jsonb;
BEGIN
    v_offset := (p_page - 1) * p_limit;

    -- Count
    SELECT COUNT(*) INTO v_total
    FROM public.licenses l
    JOIN public.licenses r ON l.referred_by_code = r.affiliate_code
    WHERE (p_search IS NULL OR l.user_name ILIKE '%' || p_search || '%' OR r.user_name ILIKE '%' || p_search || '%');

    -- Data
    SELECT jsonb_agg(t) INTO v_data
    FROM (
        SELECT 
            l.created_at,
            l.status,
            l.user_name as referee_name,
            l.plan_type,
            COALESCE(l.snapshot_discount, 0) as snapshot_discount,
            r.user_name as referrer_name,
            r.affiliate_code as referrer_code,
            r.affiliate_tier as referrer_tier,
            (SELECT price FROM public.packages WHERE name = l.plan_type LIMIT 1) as final_sale_amount,
            (SELECT SUM(amount) FROM public.affiliate_logs WHERE from_user = l.user_name AND type = 'commission') as commission_paid,
            l.commission_processed,
            0 as estimated_commission,
            0 as admin_net_profit
        FROM public.licenses l
        JOIN public.licenses r ON l.referred_by_code = r.affiliate_code
        WHERE (p_search IS NULL OR l.user_name ILIKE '%' || p_search || '%' OR r.user_name ILIKE '%' || p_search || '%')
        ORDER BY l.created_at DESC
        LIMIT p_limit OFFSET v_offset
    ) t;

    RETURN jsonb_build_object(
        'data', COALESCE(v_data, '[]'::jsonb),
        'total', v_total
    );
END;
$$;

-- 4. GLOBAL LEDGER MONITOR
CREATE OR REPLACE FUNCTION public.admin_get_global_ledger(
    p_page integer,
    p_limit integer,
    p_search text,
    p_type text
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_offset integer;
    v_total integer;
    v_data jsonb;
BEGIN
    v_offset := (p_page - 1) * p_limit;

    SELECT COUNT(*) INTO v_total
    FROM public.affiliate_logs al
    LEFT JOIN public.licenses l ON al.license_key = l.license_key
    WHERE (p_search IS NULL OR l.user_name ILIKE '%' || p_search || '%' OR al.description ILIKE '%' || p_search || '%')
    AND (p_type IS NULL OR al.type = p_type);

    SELECT jsonb_agg(t) INTO v_data
    FROM (
        SELECT 
            al.created_at,
            l.user_name,
            l.license_key,
            al.type,
            al.description,
            al.amount
        FROM public.affiliate_logs al
        LEFT JOIN public.licenses l ON al.license_key = l.license_key
        WHERE (p_search IS NULL OR l.user_name ILIKE '%' || p_search || '%' OR al.description ILIKE '%' || p_search || '%')
        AND (p_type IS NULL OR al.type = p_type)
        ORDER BY al.created_at DESC
        LIMIT p_limit OFFSET v_offset
    ) t;

    RETURN jsonb_build_object(
        'data', COALESCE(v_data, '[]'::jsonb),
        'total', v_total
    );
END;
$$;

-- 5. ADMIN ADJUST BALANCE
CREATE OR REPLACE FUNCTION public.admin_adjust_balance(
    p_license_key text,
    p_amount numeric,
    p_is_bonus boolean,
    p_reason text
) RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    IF p_is_bonus THEN
        UPDATE public.licenses SET affiliate_balance = affiliate_balance + p_amount, total_earnings = total_earnings + p_amount WHERE license_key = p_license_key;
        INSERT INTO public.affiliate_logs (license_key, amount, type, description) VALUES (p_license_key, p_amount, 'bonus', p_reason);
    ELSE
        UPDATE public.licenses SET affiliate_balance = affiliate_balance - p_amount WHERE license_key = p_license_key;
        INSERT INTO public.affiliate_logs (license_key, amount, type, description) VALUES (p_license_key, -p_amount, 'deduction', p_reason);
    END IF;
    PERFORM public.log_admin_action('ADJUST_BALANCE', p_license_key, jsonb_build_object('amount', p_amount, 'type', CASE WHEN p_is_bonus THEN 'bonus' ELSE 'deduction' END, 'reason', p_reason));
END;
$$;

-- 6. ADMIN CREATE USER
CREATE OR REPLACE FUNCTION public.admin_create_user(
    p_name text,
    p_email text,
    p_phone text,
    p_plan text,
    p_initial_credits integer,
    p_status text,
    p_affiliate_code text DEFAULT NULL,
    p_referred_by_code text DEFAULT NULL
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_new_key text;
    v_new_id bigint;
    v_ac text;
BEGIN
    v_new_key := 'TAAP-' || UPPER(SUBSTRING(MD5(RANDOM()::text) FROM 1 FOR 4)) || '-' || UPPER(SUBSTRING(MD5(RANDOM()::text) FROM 1 FOR 4)) || '-2025';
    
    INSERT INTO public.licenses (
        license_key, user_name, user_email, phone_number, plan_type, credits, status, affiliate_code, referred_by_code
    ) VALUES (
        v_new_key, p_name, p_email, p_phone, p_plan, p_initial_credits, p_status, p_affiliate_code, p_referred_by_code
    ) RETURNING id INTO v_new_id;

    IF p_affiliate_code IS NULL OR p_affiliate_code = '' THEN
        v_ac := 'TAAP-G' || LPAD(v_new_id::text, 4, '0');
        UPDATE public.licenses SET affiliate_code = v_ac WHERE id = v_new_id;
    END IF;

    PERFORM public.log_admin_action('ADMIN_CREATE_USER', v_new_key, jsonb_build_object('email', p_email));
    
    RETURN jsonb_build_object('status', 'success', 'license_key', v_new_key);
EXCEPTION WHEN OTHERS THEN
    RETURN jsonb_build_object('status', 'error', 'message', SQLERRM);
END;
$$;

-- 7. HELPERS
CREATE OR REPLACE FUNCTION public.update_bank_details(p_license_key text, p_bank text, p_acc text, p_holder text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN UPDATE public.licenses SET bank_name = p_bank, bank_details = p_acc, bank_holder = p_holder WHERE license_key = p_license_key; END; $$;

CREATE OR REPLACE FUNCTION public.check_affiliate_code(p_code text) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN PERFORM 1 FROM public.licenses WHERE affiliate_code = p_code AND status = 'active'; RETURN FOUND; END; $$;

CREATE OR REPLACE FUNCTION public.admin_get_broadcasts(p_page int, p_limit int) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE v_data jsonb;
BEGIN SELECT jsonb_agg(t) INTO v_data FROM (SELECT * FROM public.broadcasts ORDER BY created_at DESC LIMIT p_limit OFFSET (p_page - 1) * p_limit) t; RETURN jsonb_build_object('data', COALESCE(v_data, '[]'::jsonb)); END; $$;

CREATE OR REPLACE FUNCTION public.admin_create_broadcast(p_title text, p_message text, p_type text, p_is_active boolean, p_expires_at timestamptz) RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN INSERT INTO public.broadcasts (title, message, type, is_active, expires_at) VALUES (p_title, p_message, p_type, p_is_active, p_expires_at); END; $$;

CREATE OR REPLACE FUNCTION public.admin_delete_broadcast(p_id bigint) RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN DELETE FROM public.broadcasts WHERE id = p_id; END; $$;

CREATE OR REPLACE FUNCTION public.check_expired_subscriptions() RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN UPDATE public.licenses SET status = 'suspended' WHERE status = 'active' AND subscription_end_date < now(); END; $$;

CREATE OR REPLACE FUNCTION public.refund_credits(p_license_key text, p_amount int) RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN UPDATE public.licenses SET credits = credits + p_amount WHERE license_key = p_license_key; END; $$;

COMMIT;`;

export const DatabaseSetupModal: React.FC<DatabaseSetupModalProps> = ({ isOpen, onClose }) => {
  const [activeStep, setActiveStep] = useState(1);
  const [currentSql, setCurrentSql] = useState(DEFAULT_SQL_1);
  const [errorInput, setErrorInput] = useState('');
  const [isFixing, setIsFixing] = useState(false);
  const [fixStatus, setFixStatus] = useState<'idle' | 'success' | 'error'>('idle');

  // Reset SQL when step changes
  useEffect(() => {
      if (activeStep === 1) setCurrentSql(DEFAULT_SQL_1);
      if (activeStep === 2) setCurrentSql(DEFAULT_SQL_2);
      if (activeStep === 3) setCurrentSql(DEFAULT_SQL_3);
      if (activeStep === 4) setCurrentSql(DEFAULT_SQL_4);
      setErrorInput('');
      setFixStatus('idle');
  }, [activeStep]);

  const handleAiFix = async () => {
      if (!errorInput.trim()) return;
      setIsFixing(true);
      setFixStatus('idle');
      try {
          const fixed = await fixSqlScript(currentSql, errorInput);
          setCurrentSql(fixed);
          setFixStatus('success');
      } catch (e) {
          console.error(e);
          setFixStatus('error');
      } finally {
          setIsFixing(false);
      }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-fade-in">
        <div className="bg-gray-900 rounded-2xl border border-gray-800 shadow-2xl w-full max-w-5xl h-[85vh] flex flex-col overflow-hidden">
            {/* Header */}
            <div className="p-6 border-b border-gray-800 flex justify-between items-center bg-gray-950">
                <div className="flex items-center gap-3">
                    <div className="p-2 bg-blue-600 rounded-lg shadow-lg">
                        <Database className="w-5 h-5 text-white" />
                    </div>
                    <div>
                        <h3 className="text-xl font-bold text-white tracking-tight">System Database Setup</h3>
                        <p className="text-xs text-gray-500 font-medium">Schema V9.0.30 • Admin Security & Automation</p>
                    </div>
                </div>
                <button onClick={onClose} className="text-gray-400 hover:text-white p-2 rounded-lg hover:bg-gray-800 transition-colors">
                    <X className="w-5 h-5" />
                </button>
            </div>

            {/* Content */}
            <div className="flex-1 overflow-hidden flex flex-col md:flex-row">
                {/* Sidebar */}
                <div className="w-full md:w-64 bg-black border-r border-gray-800 p-4 flex flex-col gap-2 overflow-y-auto shrink-0">
                    <button onClick={() => setActiveStep(1)} className={`text-left px-4 py-3 rounded-xl text-xs font-bold flex items-center gap-3 transition-all ${activeStep === 1 ? 'bg-blue-900/30 text-blue-400 border border-blue-900/50' : 'text-gray-500 hover:bg-gray-900 hover:text-gray-300'}`}>
                        <div className={`w-6 h-6 rounded-full flex items-center justify-center text-[10px] border ${activeStep === 1 ? 'border-blue-500 bg-blue-500 text-white' : 'border-gray-700 bg-gray-800'}`}>1</div>
                        <div>
                            <span className="block">Tables & Settings</span>
                            <span className="text-[9px] opacity-70">Core Schema</span>
                        </div>
                    </button>
                    <button onClick={() => setActiveStep(2)} className={`text-left px-4 py-3 rounded-xl text-xs font-bold flex items-center gap-3 transition-all ${activeStep === 2 ? 'bg-purple-900/30 text-purple-400 border border-purple-900/50' : 'text-gray-500 hover:bg-gray-900 hover:text-gray-300'}`}>
                        <div className={`w-6 h-6 rounded-full flex items-center justify-center text-[10px] border ${activeStep === 2 ? 'border-purple-500 bg-purple-500 text-white' : 'border-gray-700 bg-gray-800'}`}>2</div>
                        <div>
                            <span className="block">Functions & Triggers</span>
                            <span className="text-[9px] opacity-70">Business Logic</span>
                        </div>
                    </button>
                    <button onClick={() => setActiveStep(3)} className={`text-left px-4 py-3 rounded-xl text-xs font-bold flex items-center gap-3 transition-all ${activeStep === 3 ? 'bg-orange-900/30 text-orange-400 border border-orange-900/50' : 'text-gray-500 hover:bg-gray-900 hover:text-gray-300'}`}>
                        <div className={`w-6 h-6 rounded-full flex items-center justify-center text-[10px] border ${activeStep === 3 ? 'border-orange-500 bg-orange-500 text-white' : 'border-gray-700 bg-gray-800'}`}>3</div>
                        <div>
                            <span className="block">Admin Logic</span>
                            <span className="text-[9px] opacity-70">Dashboard RPCs</span>
                        </div>
                    </button>
                    <button onClick={() => setActiveStep(4)} className={`text-left px-4 py-3 rounded-xl text-xs font-bold flex items-center gap-3 transition-all ${activeStep === 4 ? 'bg-green-900/30 text-green-400 border border-green-900/50' : 'text-gray-500 hover:bg-gray-900 hover:text-gray-300'}`}>
                        <div className={`w-6 h-6 rounded-full flex items-center justify-center text-[10px] border ${activeStep === 4 ? 'border-green-500 bg-green-500 text-white' : 'border-gray-700 bg-gray-800'}`}>4</div>
                        <div>
                            <span className="block">Advanced Features</span>
                            <span className="text-[9px] opacity-70">Coupons & Monitor</span>
                        </div>
                    </button>
                </div>

                {/* Main Area */}
                <div className="flex-1 bg-gray-950 flex flex-col min-w-0 border-l border-gray-800 relative">
                    <div className="p-4 border-b border-gray-800 flex justify-between items-center bg-gray-900/50">
                        <div className="flex items-center gap-2 text-xs text-gray-400">
                            <Terminal className="w-4 h-4" />
                            <span className="font-mono text-orange-500 font-bold">SQL_EDITOR_V3</span>
                        </div>
                        <CopyToClipboard text={currentSql} label="Copy SQL Script" className="bg-gray-800 hover:bg-gray-700 border-gray-700 text-gray-300" />
                    </div>
                    
                    {/* SQL Editor - Upgraded to Textarea for Editing */}
                    <div className="flex-1 relative">
                        <textarea
                            value={currentSql}
                            onChange={(e) => setCurrentSql(e.target.value)}
                            className="w-full h-full bg-[#0d1117] text-gray-300 font-mono text-xs p-4 resize-none focus:outline-none leading-relaxed"
                            spellCheck={false}
                        />
                    </div>

                    {/* AI Fixer Section - Restored functionality */}
                    <div className="p-4 border-t border-gray-800 bg-gray-900">
                        <div className="flex flex-col gap-3">
                            <div className="flex items-center justify-between">
                                <div className="flex items-center gap-2 text-xs text-gray-400">
                                    <AlertTriangle className="w-4 h-4 text-yellow-500" />
                                    <span>Got a Supabase error? Paste it below to auto-fix the SQL.</span>
                                </div>
                                {fixStatus === 'success' && <span className="text-green-500 text-xs font-bold flex items-center gap-1"><CheckCircle className="w-3 h-3"/> Fix Applied! Copy & Run Again.</span>}
                                {fixStatus === 'error' && <span className="text-red-500 text-xs font-bold">Fix Failed. Try manual edit.</span>}
                            </div>
                            
                            <div className="flex gap-2">
                                <input 
                                    value={errorInput} 
                                    onChange={(e) => setErrorInput(e.target.value)} 
                                    placeholder="Paste error message here (e.g. 'function already exists', 'syntax error')..."
                                    className="flex-1 bg-black border border-gray-700 rounded-lg px-3 py-2 text-xs text-white focus:border-orange-500 outline-none"
                                />
                                <button 
                                    onClick={handleAiFix} 
                                    disabled={isFixing || !errorInput}
                                    className="px-4 py-2 bg-gradient-to-r from-orange-600 to-red-600 hover:from-orange-500 hover:to-red-500 text-white rounded-lg text-xs font-bold flex items-center gap-2 shadow-lg disabled:opacity-50 transition-all"
                                >
                                    {isFixing ? <Loader2 className="w-3 h-3 animate-spin"/> : <Wand2 className="w-3 h-3" />}
                                    Auto-Fix SQL
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};