
import React, { useState } from 'react';
import { X, Database, Terminal, ShieldCheck, CheckCircle, ChevronRight, Play, AlertTriangle, Wand2, Loader2, Bug, TestTube } from 'lucide-react';
import { CopyToClipboard } from './CopyToClipboard';
import { fixSqlScript } from '../services/geminiService';

interface DatabaseSetupModalProps {
  isOpen: boolean;
  onClose: () => void;
}

// STEP 1: TABLES, SETTINGS & CLEANUP (Schema V9.0.18 - PAYOUT FIX)
const DEFAULT_SQL_1 = `BEGIN;
-- 1. CLEANUP OLD FUNCTIONS
DROP FUNCTION IF EXISTS public.process_payout(bigint,text,text);
DROP FUNCTION IF EXISTS public.process_payout(bigint,public.payout_status_enum,text);
DROP FUNCTION IF EXISTS public.admin_get_licenses_paginated(integer,integer,text,text,text,text);
DROP FUNCTION IF EXISTS public.admin_get_dashboard_metrics();
DROP FUNCTION IF EXISTS public.admin_update_user(bigint,text,text,text,text,text,integer,text,numeric,text,text,text,numeric,timestamptz,text,text);
DROP FUNCTION IF EXISTS public.admin_bulk_action(integer[],text);
DROP FUNCTION IF EXISTS public.admin_bulk_action(bigint[],text); 
DROP FUNCTION IF EXISTS public.request_payout(text,numeric,text);
DROP TRIGGER IF EXISTS on_license_status_change ON public.licenses;
DROP FUNCTION IF EXISTS public.process_referral_commission();

-- 2. CREATE TABLES
CREATE TABLE IF NOT EXISTS public.licenses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz DEFAULT now() NOT NULL,
    license_key text UNIQUE NOT NULL,
    user_name text,
    user_email text,
    phone_number text,
    plan_type text DEFAULT 'Starter',
    credits integer DEFAULT 0,
    status text DEFAULT 'pending',
    subscription_end_date timestamptz,
    affiliate_code text UNIQUE,
    referred_by_code text,
    affiliate_balance numeric DEFAULT 0,
    total_earnings numeric DEFAULT 0,
    affiliate_tier text DEFAULT 'Agent',
    successful_referrals integer DEFAULT 0,
    custom_commission_rate numeric,
    bank_name text,
    bank_details text,
    bank_holder text,
    updated_at timestamptz DEFAULT now(),
    snapshot_discount numeric DEFAULT 0,
    snapshot_commission_rate numeric DEFAULT 0,
    commission_processed boolean DEFAULT false,
    admin_notes text
);

CREATE TABLE IF NOT EXISTS public.affiliate_logs (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,created_at timestamptz DEFAULT now() NOT NULL,license_key text NOT NULL,amount numeric NOT NULL,type text NOT NULL,description text,from_user text,commission_rate numeric,source_amount numeric);
CREATE TABLE IF NOT EXISTS public.payout_requests (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,created_at timestamptz DEFAULT now() NOT NULL,license_key text NOT NULL,amount numeric NOT NULL,status text DEFAULT 'pending',bank_details text,admin_note text,processed_at timestamptz);
CREATE TABLE IF NOT EXISTS public.broadcasts (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,created_at timestamptz DEFAULT now() NOT NULL,title text NOT NULL,message text NOT NULL,type text DEFAULT 'info',is_active boolean DEFAULT true,expires_at timestamptz);
CREATE TABLE IF NOT EXISTS public.audit_trail (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,created_at timestamptz DEFAULT now() NOT NULL,admin_actor text DEFAULT 'System',action text NOT NULL,target_license_key text,details jsonb);
CREATE TABLE IF NOT EXISTS public.system_settings (key text PRIMARY KEY,value text,description text);
CREATE TABLE IF NOT EXISTS public.coupons (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,code text UNIQUE NOT NULL,discount_type text DEFAULT 'percentage',discount_value numeric NOT NULL,is_active boolean DEFAULT true,usage_limit integer DEFAULT 100,used_count integer DEFAULT 0,created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.packages (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name text NOT NULL,price numeric NOT NULL,credits int NOT NULL,features jsonb DEFAULT '[]'::jsonb,is_active boolean DEFAULT true,is_popular boolean DEFAULT false,ref_code text,period text DEFAULT '/ month',old_price numeric,credit_label text,color_theme text DEFAULT 'blue',created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.feedback_logs (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at timestamptz DEFAULT now(), license_key text, rating text, content_snippet text);

-- 3. SEED INITIAL DATA
INSERT INTO public.packages (name,price,credits,features,is_popular,ref_code,old_price,credit_label,color_theme) SELECT 'Basic Plan',69,200,'["Auto-Fill & Manual Input","Access to Neural Engine V4","Normal Speed","Email Support","GenPro Studio LOCKED"]'::jsonb,false,'BASIC-M',null,'200 Credits / Month','blue' WHERE NOT EXISTS (SELECT 1 FROM public.packages WHERE name='Basic Plan');
INSERT INTO public.packages (name,price,credits,features,is_popular,ref_code,old_price,credit_label,color_theme) SELECT 'TAAP PRO',199,600,'["Massive 600 Credits","GenPro Studio (Image Gen)","Viral Trend Search","Priority Queue"]'::jsonb,true,'PRO-M',299,'600 Credits / Month','orange' WHERE NOT EXISTS (SELECT 1 FROM public.packages WHERE name='TAAP PRO');

INSERT INTO public.system_settings (key,value,description) VALUES 
('cost_per_generation','1','Cost per text'),
('cost_per_autofill','1','Cost per autofill'),
('cost_per_image_generation','2','Cost per Imagen'),
('cost_per_video_generation','10','Cost per Veo'),
('referral_discount_percent','5','Discount for new users via referral'),
('affiliate_commission_agent','10','Agent Commission %'),
('affiliate_commission_super','15','Super Agent Commission %'),
('affiliate_commission_partner','20','Partner Commission %'),
('tier_req_super_agent','10','Referrals required for Super Agent'),
('tier_req_partner','50','Referrals required for Partner'),
('admin_whatsapp','60176162761','Admin Contact Number'),
('payment_qr_url', 'https://lh3.googleusercontent.com/d/1AlmtkkZgELIA_zul3vGsWQ36zJ73X3wI', 'DuitNow QR Image URL') 
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

-- 4. DB MIGRATION: PAYOUT STATUS FIX & CONSTRAINT REBUILD
DO $$ 
DECLARE
    r RECORD;
BEGIN 
    -- MIGRATE LEGACY 'declined' STATUS TO 'rejected'
    -- This must run before adding the new constraint.
    UPDATE public.payout_requests SET status = 'rejected' WHERE status = 'declined';

    -- DYNAMICALLY FIND AND DROP ALL CHECK CONSTRAINTS ON PAYOUT_REQUESTS
    FOR r IN (
        SELECT con.conname
        FROM pg_catalog.pg_constraint con
        INNER JOIN pg_catalog.pg_class rel ON rel.oid = con.conrelid
        INNER JOIN pg_catalog.pg_namespace nsp ON nsp.oid = connamespace
        WHERE nsp.nspname = 'public'
          AND rel.relname = 'payout_requests'
          AND con.contype = 'c' -- Check constraint
    ) LOOP
        EXECUTE 'ALTER TABLE public.payout_requests DROP CONSTRAINT IF EXISTS ' || quote_ident(r.conname);
    END LOOP;

    -- Force column to TEXT to remove any Enum dependencies
    ALTER TABLE public.payout_requests ALTER COLUMN status TYPE text;
    
    -- Reset default to ensure consistency
    ALTER TABLE public.payout_requests ALTER COLUMN status SET DEFAULT 'pending';
    
    -- ADD A NEW, CORRECT CONSTRAINT to prevent future invalid values
    ALTER TABLE public.payout_requests DROP CONSTRAINT IF EXISTS payout_status_valid_values;
    ALTER TABLE public.payout_requests ADD CONSTRAINT payout_status_valid_values CHECK (status IN ('pending', 'approved', 'rejected'));

    -- Ensure other columns exist (idempotent checks)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='licenses' AND column_name='commission_processed') THEN 
        ALTER TABLE public.licenses ADD COLUMN commission_processed boolean DEFAULT false; 
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='licenses' AND column_name='snapshot_discount') THEN 
        ALTER TABLE public.licenses ADD COLUMN snapshot_discount numeric DEFAULT 0; 
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='licenses' AND column_name='snapshot_commission_rate') THEN 
        ALTER TABLE public.licenses ADD COLUMN snapshot_commission_rate numeric DEFAULT 0; 
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='licenses' AND column_name='admin_notes') THEN 
        ALTER TABLE public.licenses ADD COLUMN admin_notes text; 
    END IF;
END $$;

COMMIT;`;

// STEP 2: CORE TRIGGERS (Schema V9.0.8)
const DEFAULT_SQL_2 = `BEGIN;
-- LOGGING HELPER
CREATE OR REPLACE FUNCTION public.log_admin_action(p_action text,p_target text,p_details jsonb) RETURNS void LANGUAGE plpgsql AS $$ BEGIN INSERT INTO public.audit_trail (action,target_license_key,details) VALUES (p_action,p_target,p_details); END; $$;

-- AFFILIATE COMMISSION TRIGGER
CREATE OR REPLACE FUNCTION public.process_referral_commission() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$ 
DECLARE 
  v_rkey text; 
  v_tier text; 
  v_count int; 
  v_rate numeric; 
  v_custom numeric; 
  v_price numeric; 
  v_comm numeric; 
  v_discount_used numeric;
  v_should_process boolean := false;
  v_locked_rate numeric;
  
  -- Dynamic Settings Variables
  v_req_super int;
  v_req_partner int;
  v_rate_agent numeric;
  v_rate_super numeric;
  v_rate_partner numeric;
BEGIN 
  IF (TG_OP = 'INSERT') THEN
      IF NEW.status = 'active' THEN v_should_process := true; END IF;
  ELSIF (TG_OP = 'UPDATE') THEN
      IF NEW.status = 'active' AND OLD.status != 'active' THEN v_should_process := true; END IF;
  END IF;

  IF v_should_process AND NEW.referred_by_code IS NOT NULL AND (NEW.commission_processed IS NULL OR NEW.commission_processed = false) THEN 
    BEGIN
        SELECT license_key,affiliate_tier,successful_referrals,custom_commission_rate INTO v_rkey,v_tier,v_count,v_custom FROM public.licenses WHERE affiliate_code=NEW.referred_by_code; 
        
        -- Load Dynamic Settings
        SELECT value::int INTO v_req_super FROM public.system_settings WHERE key='tier_req_super_agent';
        SELECT value::int INTO v_req_partner FROM public.system_settings WHERE key='tier_req_partner';
        SELECT value::numeric INTO v_rate_agent FROM public.system_settings WHERE key='affiliate_commission_agent';
        SELECT value::numeric INTO v_rate_super FROM public.system_settings WHERE key='affiliate_commission_super';
        SELECT value::numeric INTO v_rate_partner FROM public.system_settings WHERE key='affiliate_commission_partner';
        
        -- Default Fallbacks
        v_req_super := COALESCE(v_req_super, 10);
        v_req_partner := COALESCE(v_req_partner, 50);
        v_rate_agent := COALESCE(v_rate_agent, 10.0);
        v_rate_super := COALESCE(v_rate_super, 15.0);
        v_rate_partner := COALESCE(v_rate_partner, 20.0);

        IF v_rkey IS NOT NULL AND v_rkey!=NEW.license_key THEN 
          -- FIX: DYNAMIC PRICE LOOKUP FROM PACKAGES TABLE
          SELECT price INTO v_price FROM public.packages WHERE name = NEW.plan_type;
          v_price := COALESCE(v_price, 69.00);

          v_discount_used := COALESCE(NEW.snapshot_discount, 0);
          IF v_discount_used > 0 THEN v_price := v_price - (v_price * (v_discount_used / 100.0)); END IF;
          
          -- Rate Logic
          v_locked_rate := COALESCE(NEW.snapshot_commission_rate, 0);
          IF v_locked_rate > 0 THEN v_rate := v_locked_rate; 
          ELSE
             IF v_custom IS NOT NULL THEN v_rate:=v_custom; 
             ELSIF v_tier='Partner' THEN v_rate:=v_rate_partner; 
             ELSIF v_tier='Super Agent' THEN v_rate:=v_rate_super; 
             ELSE v_rate:=v_rate_agent; 
             END IF; 
          END IF;
          
          v_comm := v_price * (v_rate / 100.0); 
          INSERT INTO public.affiliate_logs (license_key,amount,type,description,from_user,commission_rate,source_amount) 
          VALUES (v_rkey,v_comm,'commission','Comm: '||NEW.user_name,NEW.user_name,v_rate,v_price); 
          
          UPDATE public.licenses SET affiliate_balance=affiliate_balance+v_comm,total_earnings=total_earnings+v_comm,successful_referrals=successful_referrals+1 WHERE license_key=v_rkey; 
          
          -- Tier Upgrade Logic
          v_count:=v_count+1; 
          IF v_tier='Agent' AND v_count >= v_req_super THEN 
              UPDATE public.licenses SET affiliate_tier='Super Agent' WHERE license_key=v_rkey; 
          ELSIF v_tier='Super Agent' AND v_count >= v_req_partner THEN 
              UPDATE public.licenses SET affiliate_tier='Partner' WHERE license_key=v_rkey; 
          END IF;
        END IF; 
        NEW.commission_processed := true;
    EXCEPTION WHEN OTHERS THEN
        INSERT INTO public.audit_trail (action, target_license_key, details) VALUES ('COMMISSION_ERROR', NEW.license_key, jsonb_build_object('error', SQLERRM));
    END;
  END IF; 
  RETURN NEW; 
END; 
$$;

DROP TRIGGER IF EXISTS on_license_status_change ON public.licenses;
CREATE TRIGGER on_license_status_change BEFORE INSERT OR UPDATE ON public.licenses FOR EACH ROW EXECUTE FUNCTION public.process_referral_commission();

-- GET REFERRALS
CREATE OR REPLACE FUNCTION public.get_user_referrals(p_license_key text) RETURNS TABLE (user_name text,plan_type text,joined_at timestamptz,status text,commission_earned numeric, snapshot_discount numeric, snapshot_commission_rate numeric, commission_processed boolean) LANGUAGE plpgsql SECURITY DEFINER AS $$ 
DECLARE v_code text; 
BEGIN 
  SELECT affiliate_code INTO v_code FROM public.licenses WHERE license_key=p_license_key; 
  IF v_code IS NULL THEN RETURN; END IF; 
  RETURN QUERY 
  SELECT l.user_name,l.plan_type,l.created_at,l.status,COALESCE((SELECT SUM(amount) FROM public.affiliate_logs al WHERE al.from_user=l.user_name AND al.license_key=p_license_key AND al.type='commission'),0)::numeric,COALESCE(l.snapshot_discount, 0)::numeric,COALESCE(l.snapshot_commission_rate, 0)::numeric,COALESCE(l.commission_processed, false)
  FROM public.licenses l WHERE l.referred_by_code=v_code ORDER BY l.created_at DESC; 
END; 
$$;

-- NEW REGISTRATION
CREATE OR REPLACE FUNCTION public.register_new_user(p_license_key text,p_name text,p_email text,p_phone text,p_plan text,p_referral_code text,p_snapshot_discount numeric) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER AS $$ 
DECLARE 
  v_new_id bigint;
  v_ac text; 
  v_upline_rate numeric := 0;
  v_upline_tier text;
  v_upline_custom numeric;
  v_rate_agent numeric;
  v_rate_super numeric;
  v_rate_partner numeric;
  v_verified_discount numeric := 0;
BEGIN 
  PERFORM 1 FROM public.licenses WHERE user_email=p_email; 
  IF FOUND THEN RETURN jsonb_build_object('status','error','message','Email already registered'); END IF; 
  
  -- Load Dynamic Rates for Snapshot
  SELECT value::numeric INTO v_rate_agent FROM public.system_settings WHERE key='affiliate_commission_agent';
  SELECT value::numeric INTO v_rate_super FROM public.system_settings WHERE key='affiliate_commission_super';
  SELECT value::numeric INTO v_rate_partner FROM public.system_settings WHERE key='affiliate_commission_partner';
  v_rate_agent := COALESCE(v_rate_agent, 10.0);
  v_rate_super := COALESCE(v_rate_super, 15.0);
  v_rate_partner := COALESCE(v_rate_partner, 20.0);

  -- Snapshot Logic
  IF p_referral_code IS NOT NULL AND p_referral_code != '' THEN
      SELECT affiliate_tier, custom_commission_rate INTO v_upline_tier, v_upline_custom 
      FROM public.licenses WHERE affiliate_code = p_referral_code;
      
      IF FOUND THEN
          SELECT value::numeric INTO v_verified_discount FROM public.system_settings WHERE key='referral_discount_percent';
          v_verified_discount := COALESCE(v_verified_discount, 0);

          if v_upline_custom IS NOT NULL THEN v_upline_rate := v_upline_custom;
          ELSIF v_upline_tier = 'Partner' THEN v_upline_rate := v_rate_partner;
          ELSIF v_upline_tier = 'Super Agent' THEN v_upline_rate := v_rate_super;
          ELSE v_upline_rate := v_rate_agent;
          END IF;
      END IF;
  END IF;

  INSERT INTO public.licenses (
      license_key,user_name,user_email,phone_number,plan_type,credits,status,affiliate_code,referred_by_code, snapshot_discount, snapshot_commission_rate, subscription_end_date
  ) VALUES (
      v_key,p_name,p_email,p_phone,p_plan,p_initial_credits,p_status, CASE WHEN p_affiliate_code IS NOT NULL AND p_affiliate_code != '' THEN p_affiliate_code ELSE NULL END, p_referred_by_code, COALESCE(v_disc, 0), COALESCE(v_upline_rate, 0), v_expiry
  ) RETURNING id INTO v_new_id; 
  
  IF p_affiliate_code IS NULL OR p_affiliate_code = '' THEN v_ac := 'TAAP-G' || LPAD(v_new_id::text, 4, '0'); UPDATE public.licenses SET affiliate_code = v_ac WHERE id = v_new_id; END IF;
  
  PERFORM public.log_admin_action('CREATE_USER',v_key,jsonb_build_object('email',p_email)); 
  RETURN jsonb_build_object('status','success','license_key',v_key); 
  EXCEPTION WHEN OTHERS THEN RETURN jsonb_build_object('status','error','message',SQLERRM); 
END; 
$$;

-- REQUEST PAYOUT
CREATE OR REPLACE FUNCTION public.request_payout(p_license_key text, p_amount numeric, p_bank_details text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER AS $$ DECLARE v_bal numeric; BEGIN SELECT affiliate_balance INTO v_bal FROM public.licenses WHERE license_key=p_license_key; IF v_bal<p_amount THEN RETURN jsonb_build_object('status','error','message','Insufficient balance'); END IF; UPDATE public.licenses SET affiliate_balance=affiliate_balance-p_amount WHERE license_key=p_license_key; INSERT INTO public.payout_requests(license_key,amount,bank_details) VALUES (p_license_key,p_amount,p_bank_details); INSERT INTO public.affiliate_logs(license_key,amount,type,description) VALUES (p_license_key,-p_amount,'payout_request','Withdrawal'); RETURN jsonb_build_object('status','success'); END; $$;

-- UPDATE BANK
CREATE OR REPLACE FUNCTION public.update_bank_details(p_license_key text, p_bank text, p_acc text, p_holder text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER AS $$ BEGIN UPDATE public.licenses SET bank_name=p_bank,bank_details=p_acc,bank_holder=p_holder WHERE license_key=p_license_key; RETURN jsonb_build_object('status','success'); END; $$;

-- GRANT EXECUTE ON SECURE RPCS
GRANT EXECUTE ON FUNCTION public.register_new_user(text, text, text, text, text, text, numeric) TO anon;
GRANT EXECUTE ON FUNCTION public.request_payout(text, numeric, text) TO anon;
GRANT EXECUTE ON FUNCTION public.update_bank_details(text, text, text, text) TO anon;
GRANT EXECUTE ON FUNCTION public.get_user_referrals(text) TO anon;

COMMIT;`;

// STEP 3: ADMIN & UTILITY FUNCTIONS (Schema V9.0.15 - STRICT STATUS UPDATE)
const DEFAULT_SQL_3 = `BEGIN;
-- ADMIN UPDATE USER
CREATE OR REPLACE FUNCTION public.admin_update_user(p_id bigint,p_name text,p_email text,p_phone text,p_plan text,p_status text,p_credits integer,p_tier text,p_custom_rate numeric,p_bank_name text,p_bank_acc text,p_bank_holder text,p_balance numeric,p_expiry timestamptz,p_affiliate_code text,p_referred_by_code text,p_snapshot_discount numeric,p_snapshot_commission_rate numeric,p_admin_notes text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ 
BEGIN 
  UPDATE public.licenses SET 
    user_name=p_name, phone_number=p_phone, plan_type=p_plan, status=p_status, credits=p_credits, affiliate_tier=p_tier, custom_commission_rate=p_custom_rate, bank_name=p_bank_name, bank_details=p_bank_acc, bank_holder=p_bank_holder, affiliate_balance=p_balance, subscription_end_date=p_expiry, affiliate_code=p_affiliate_code, referred_by_code=p_referred_by_code, snapshot_discount=p_snapshot_discount, snapshot_commission_rate=p_snapshot_commission_rate, admin_notes=p_admin_notes, updated_at=now() 
  WHERE id=p_id; 
  PERFORM public.log_admin_action('UPDATE_USER',(SELECT license_key FROM public.licenses WHERE id=p_id),jsonb_build_object('status',p_status)); 
  RETURN jsonb_build_object('status','success'); 
EXCEPTION WHEN OTHERS THEN 
  RETURN jsonb_build_object('status','error','message',SQLERRM); 
END; 
$$;

-- ADMIN CREATE USER
CREATE OR REPLACE FUNCTION public.admin_create_user(p_name text,p_email text,p_phone text,p_plan text,p_initial_credits integer,p_status text,p_affiliate_code text,p_referred_by_code text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ 
DECLARE 
  v_key text; v_ac text; v_new_id bigint; v_disc numeric := 0; v_upline_rate numeric := 0; v_upline_tier text; v_upline_custom numeric; v_rate_agent numeric; v_rate_super numeric; v_rate_partner numeric; v_expiry timestamptz;
BEGIN 
  v_key:='TAAP-'||floor(random()*9000+1000)::text||'-'||floor(random()*9000+1000)::text||'-ADM'; 
  IF p_status = 'active' THEN v_expiry := now() + interval '30 days'; ELSE v_expiry := NULL; END IF;
  SELECT value::numeric INTO v_rate_agent FROM public.system_settings WHERE key='affiliate_commission_agent';
  SELECT value::numeric INTO v_rate_super FROM public.system_settings WHERE key='affiliate_commission_super';
  SELECT value::numeric INTO v_rate_partner FROM public.system_settings WHERE key='affiliate_commission_partner';
  v_rate_agent := COALESCE(v_rate_agent, 10.0); v_rate_super := COALESCE(v_rate_super, 15.0); v_rate_partner := COALESCE(v_rate_partner, 20.0);

  IF p_referred_by_code IS NOT NULL AND p_referred_by_code != '' THEN
      SELECT value::numeric INTO v_disc FROM public.system_settings WHERE key='referral_discount_percent';
      SELECT affiliate_tier, custom_commission_rate INTO v_upline_tier, v_upline_custom FROM public.licenses WHERE affiliate_code = p_referred_by_code;
      IF FOUND THEN
          IF v_upline_custom IS NOT NULL THEN v_upline_rate := v_upline_custom;
          ELSIF v_upline_tier = 'Partner' THEN v_upline_rate := v_rate_partner;
          ELSIF v_upline_tier = 'Super Agent' THEN v_upline_rate := v_rate_super;
          ELSE v_upline_rate := v_rate_agent;
          END IF;
      END IF;
  END IF;

  INSERT INTO public.licenses (
      license_key,user_name,user_email,phone_number,plan_type,credits,status,affiliate_code,referred_by_code, snapshot_discount, snapshot_commission_rate, subscription_end_date
  ) VALUES (
      v_key,p_name,p_email,p_phone,p_plan,p_initial_credits,p_status, CASE WHEN p_affiliate_code IS NOT NULL AND p_affiliate_code != '' THEN p_affiliate_code ELSE NULL END, p_referred_by_code, COALESCE(v_disc, 0), COALESCE(v_upline_rate, 0), v_expiry
  ) RETURNING id INTO v_new_id; 
  
  IF p_affiliate_code IS NULL OR p_affiliate_code = '' THEN v_ac := 'TAAP-G' || LPAD(v_new_id::text, 4, '0'); UPDATE public.licenses SET affiliate_code = v_ac WHERE id = v_new_id; END IF;
  
  PERFORM public.log_admin_action('CREATE_USER',v_key,jsonb_build_object('email',p_email)); 
  RETURN jsonb_build_object('status','success','license_key',v_key); 
  EXCEPTION WHEN OTHERS THEN RETURN jsonb_build_object('status','error','message',SQLERRM); 
END; 
$$;

-- PROCESS PAYOUT (V9.0.15 - STRICT UPDATE)
CREATE OR REPLACE FUNCTION public.process_payout(p_payout_id bigint, p_status text, p_admin_note text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ 
DECLARE 
  v_req record;
  v_new_status text;
BEGIN 
  SELECT * INTO v_req FROM public.payout_requests WHERE id=p_payout_id; 
  IF NOT FOUND THEN RETURN jsonb_build_object('status','error','message','Payout ID not found'); END IF; 
  
  -- Force UPDATE (Works even if column was formerly enum)
  UPDATE public.payout_requests 
  SET status = p_status, 
      admin_note = p_admin_note, 
      processed_at = now() 
  WHERE id = p_payout_id 
  RETURNING status INTO v_new_status; 
  
  -- Handle Refund
  IF p_status = 'rejected' THEN 
    UPDATE public.licenses SET affiliate_balance = affiliate_balance + v_req.amount WHERE license_key = v_req.license_key; 
    INSERT INTO public.affiliate_logs(license_key, amount, type, description) VALUES (v_req.license_key, v_req.amount, 'refund', 'Refund: ' || p_admin_note); 
  END IF; 
  
  PERFORM public.log_admin_action('PROCESS_PAYOUT', v_req.license_key, jsonb_build_object('id', p_payout_id, 'status', p_status)); 
  
  RETURN jsonb_build_object('status', 'success', 'new_status', v_new_status); 
EXCEPTION WHEN OTHERS THEN
  RETURN jsonb_build_object('status', 'error', 'message', SQLERRM);
END; $$;

-- ADMIN ADJUST BALANCE
CREATE OR REPLACE FUNCTION public.admin_adjust_balance(p_license_key text, p_amount numeric, p_is_bonus boolean, p_reason text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE v_fin numeric; BEGIN IF p_is_bonus THEN v_fin:=p_amount; ELSE v_fin:=-p_amount; END IF; UPDATE public.licenses SET affiliate_balance=affiliate_balance+v_fin,updated_at=now() WHERE license_key=p_license_key; INSERT INTO public.affiliate_logs(license_key,amount,type,description) VALUES (p_license_key,v_fin,CASE WHEN p_is_bonus THEN 'bonus' ELSE 'deduction' END,p_reason); PERFORM public.log_admin_action('ADJUST_WALLET',p_license_key,jsonb_build_object('amt',v_fin)); RETURN jsonb_build_object('status','success'); END; $$;

-- ADMIN BULK ACTION
CREATE OR REPLACE FUNCTION public.admin_bulk_action(p_ids bigint[], p_action text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE v_cnt integer; BEGIN IF p_action='delete' THEN DELETE FROM public.licenses WHERE id=ANY(p_ids); GET DIAGNOSTICS v_cnt=ROW_COUNT; ELSIF p_action='approve' THEN UPDATE public.licenses SET status='active', subscription_end_date = now() + interval '30 days' WHERE id=ANY(p_ids); GET DIAGNOSTICS v_cnt=ROW_COUNT; ELSIF p_action='suspend' THEN UPDATE public.licenses SET status='suspended' WHERE id=ANY(p_ids); GET DIAGNOSTICS v_cnt=ROW_COUNT; END IF; PERFORM public.log_admin_action('BULK_'||UPPER(p_action),'MULTIPLE',jsonb_build_object('cnt',v_cnt)); RETURN jsonb_build_object('status','success','count',v_cnt); END; $$;

-- ADMIN GET LICENSES PAGINATED
CREATE OR REPLACE FUNCTION public.admin_get_licenses_paginated(p_page integer, p_limit integer, p_sort_by text, p_sort_dir text, p_search_term text, p_ref_filter text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_off integer; v_tot integer; v_dat jsonb;
BEGIN
    v_off := (p_page - 1) * p_limit;
    SELECT COUNT(*) INTO v_tot FROM public.licenses WHERE (p_search_term IS NULL OR user_name ILIKE '%'||p_search_term||'%' OR user_email ILIKE '%'||p_search_term||'%');
    SELECT jsonb_agg(t) INTO v_dat FROM (
        SELECT * FROM public.licenses 
        WHERE (p_search_term IS NULL OR user_name ILIKE '%'||p_search_term||'%' OR user_email ILIKE '%'||p_search_term||'%')
        ORDER BY created_at DESC LIMIT p_limit OFFSET v_off
    ) t;
    RETURN jsonb_build_object('data', COALESCE(v_dat, '[]'::jsonb), 'total', v_tot);
END;
$$;

-- MISC FUNCTIONS
CREATE OR REPLACE FUNCTION public.check_expired_subscriptions() RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$ BEGIN UPDATE public.licenses SET status = 'suspended' WHERE status = 'active' AND subscription_end_date < now(); END; $$;
CREATE OR REPLACE FUNCTION public.admin_get_dashboard_metrics() RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE v_tot int; v_act int; v_aff int; v_pen_c int; v_pen_a numeric; BEGIN SELECT COUNT(*) INTO v_tot FROM public.licenses; SELECT COUNT(*) INTO v_act FROM public.licenses WHERE status='active'; SELECT COUNT(*) INTO v_aff FROM public.licenses WHERE successful_referrals>0; SELECT COUNT(*),COALESCE(SUM(amount),0) INTO v_pen_c,v_pen_a FROM public.payout_requests WHERE status='pending'; RETURN jsonb_build_object('total_licenses',v_tot,'active_licenses',v_act,'total_affiliates',v_aff,'affiliate_conversion_rate',0,'total_lifetime_affiliate_earnings',(SELECT COALESCE(SUM(total_earnings),0) FROM public.licenses),'pending_payouts_count',v_pen_c,'pending_payouts_amount',v_pen_a,'total_credits_consumed',0); END; $$;
CREATE OR REPLACE FUNCTION public.admin_get_broadcasts(p_page int,p_limit int) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER AS $$ DECLARE v_d jsonb; BEGIN SELECT jsonb_agg(t) INTO v_d FROM (SELECT * FROM public.broadcasts ORDER BY created_at DESC LIMIT p_limit OFFSET (p_page-1)*p_limit) t; RETURN jsonb_build_object('data',COALESCE(v_d,'[]'::jsonb)); END; $$;
CREATE OR REPLACE FUNCTION public.admin_create_broadcast(p_title text, p_message text, p_type text, p_is_active boolean, p_expires_at timestamptz) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER AS $$ BEGIN INSERT INTO public.broadcasts (title,message,type,is_active,expires_at) VALUES (p_title,p_message,p_type,p_is_active,p_expires_at); RETURN jsonb_build_object('status','success'); END; $$;
CREATE OR REPLACE FUNCTION public.admin_delete_broadcast(p_id bigint) RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$ BEGIN DELETE FROM public.broadcasts WHERE id=p_id; END; $$;
CREATE OR REPLACE FUNCTION public.admin_get_audit_trail(p_page int, p_limit int, p_search_action text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER AS $$ DECLARE v_d jsonb; BEGIN SELECT jsonb_agg(t) INTO v_d FROM (SELECT * FROM public.audit_trail WHERE (p_search_action IS NULL OR action ILIKE '%'||p_search_action||'%') ORDER BY created_at DESC LIMIT p_limit OFFSET (p_page-1)*p_limit) t; RETURN jsonb_build_object('data',COALESCE(v_d,'[]'::jsonb)); END; $$;
CREATE OR REPLACE FUNCTION public.deduct_credits(p_license_key text, p_amount int, p_type text) RETURNS int LANGUAGE plpgsql SECURITY DEFINER AS $$ DECLARE v_c int; v_cost int; v_setting_key text; BEGIN IF p_type = 'text_generation' THEN v_setting_key := 'cost_per_generation'; ELSIF p_type = 'autofill' THEN v_setting_key := 'cost_per_autofill'; ELSIF p_type = 'image_generation' THEN v_setting_key := 'cost_per_image_generation'; ELSIF p_type = 'video_generation' THEN v_setting_key := 'cost_per_video_generation'; ELSE v_setting_key := 'cost_per_generation'; END IF; SELECT value::int INTO v_cost FROM public.system_settings WHERE key = v_setting_key; v_cost := COALESCE(v_cost, 1); UPDATE public.licenses SET credits = credits - v_cost, last_used_at = now() WHERE license_key = p_license_key RETURNING credits INTO v_c; IF v_c < 0 THEN RAISE EXCEPTION 'Insufficient credits'; END IF; RETURN v_c; END; $$;
CREATE OR REPLACE FUNCTION public.refund_credits(p_license_key text, p_amount int) RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$ BEGIN UPDATE public.licenses SET credits=credits+p_amount WHERE license_key=p_license_key; END; $$;
CREATE OR REPLACE FUNCTION public.admin_get_affiliate_leaderboard() RETURNS TABLE (user_name text,license_key text,masked_key text,total_earnings numeric,affiliate_tier text,referral_count integer) LANGUAGE plpgsql SECURITY DEFINER AS $$ BEGIN RETURN QUERY SELECT user_name,license_key,'****'::text,COALESCE(total_earnings,0),affiliate_tier,COALESCE(successful_referrals,0) FROM public.licenses WHERE total_earnings>0 ORDER BY total_earnings DESC LIMIT 10; END; $$;
CREATE OR REPLACE FUNCTION public.verify_coupon(p_code text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER AS $$ DECLARE v_c record; BEGIN SELECT * INTO v_c FROM public.coupons WHERE code=p_code AND is_active=true; IF NOT FOUND THEN RETURN jsonb_build_object('status','error'); END IF; RETURN jsonb_build_object('status','success','data',jsonb_build_object('code',v_c.code,'type',v_c.discount_type,'value',v_c.discount_value)); END; $$;
CREATE OR REPLACE FUNCTION public.check_affiliate_code(p_code text) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER AS $$ BEGIN PERFORM 1 FROM public.licenses WHERE affiliate_code=p_code; RETURN FOUND; END; $$;

-- PERMISSIONS (STRICT LOCKDOWN V2)
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM anon;
GRANT USAGE ON SCHEMA public TO anon;
GRANT SELECT ON public.system_settings TO anon;
GRANT SELECT ON public.packages TO anon;
GRANT SELECT ON public.broadcasts TO anon;
GRANT SELECT ON public.coupons TO anon;
GRANT SELECT ON public.licenses TO anon;
GRANT SELECT ON public.payout_requests TO anon;
GRANT SELECT ON public.affiliate_logs TO anon;
GRANT SELECT ON public.audit_trail TO anon;
GRANT SELECT ON public.feedback_logs TO anon;
GRANT EXECUTE ON FUNCTION public.deduct_credits(text, int, text) TO anon;
GRANT EXECUTE ON FUNCTION public.refund_credits(text, int) TO anon;
GRANT EXECUTE ON FUNCTION public.verify_coupon(text) TO anon;
GRANT EXECUTE ON FUNCTION public.check_affiliate_code(text) TO anon;
GRANT EXECUTE ON FUNCTION public.admin_get_dashboard_metrics() TO anon;
GRANT EXECUTE ON FUNCTION public.admin_get_licenses_paginated(integer, integer, text, text, text, text) TO anon;
GRANT EXECUTE ON FUNCTION public.admin_create_user(text, text, text, text, integer, text, text, text) TO anon;
GRANT EXECUTE ON FUNCTION public.admin_update_user(bigint, text, text, text, text, text, integer, text, numeric, text, text, text, numeric, timestamptz, text, text, numeric, numeric, text) TO anon;
GRANT EXECUTE ON FUNCTION public.admin_bulk_action(bigint[], text) TO anon;
GRANT EXECUTE ON FUNCTION public.admin_adjust_balance(text, numeric, boolean, text) TO anon;
GRANT EXECUTE ON FUNCTION public.admin_get_broadcasts(int, int) TO anon;
GRANT EXECUTE ON FUNCTION public.admin_create_broadcast(text, text, text, boolean, timestamptz) TO anon;
GRANT EXECUTE ON FUNCTION public.admin_delete_broadcast(bigint) TO anon;
GRANT EXECUTE ON FUNCTION public.admin_get_audit_trail(int, int, text) TO anon;
GRANT EXECUTE ON FUNCTION public.admin_get_affiliate_leaderboard() TO anon;
GRANT EXECUTE ON FUNCTION public.process_payout(bigint, text, text) TO anon; -- MOVED HERE
GRANT EXECUTE ON FUNCTION public.check_expired_subscriptions() TO anon;
GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO service_role;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO service_role;

COMMIT;`;

const SIMULATION_SQL = `BEGIN;
-- SIMULATION DATA (V9.0.2)
INSERT INTO public.licenses (created_at, license_key, user_name, user_email, phone_number, plan_type, credits, status, affiliate_code, affiliate_tier, affiliate_balance, total_earnings, successful_referrals)
VALUES (NOW() - INTERVAL '30 days', 'SIM-SIFU-001', 'Big Sifu', 'sifu@sim.com', '0123456789', 'TAAP PRO', 5000, 'active', 'SIFU888', 'Agent', 0, 0, 0)
ON CONFLICT (license_key) DO NOTHING;

INSERT INTO public.licenses (created_at, license_key, user_name, user_email, phone_number, plan_type, credits, status, referred_by_code, affiliate_code, snapshot_discount, snapshot_commission_rate)
VALUES (NOW(), 'SIM-ALI-002', 'Newbie Ali', 'ali@sim.com', '0198765432', 'TAAP PRO', 600, 'active', 'SIFU888', 'TAAP-GSIM', 5, 10)
ON CONFLICT (license_key) DO NOTHING;

INSERT INTO public.licenses (license_key, user_name, user_email, plan_type, status, affiliate_balance, affiliate_code)
VALUES (NOW(), 'SIM-RICH-003', 'Rich Guy', 'rich@sim.com', 'TAAP PRO', 'active', 500, 'RICH777')
ON CONFLICT (license_key) DO NOTHING;

INSERT INTO public.payout_requests (created_at, license_key, amount, status, bank_details)
VALUES (NOW(), 'SIM-RICH-003', 250.00, 'pending', 'Maybank 1144556677');

COMMIT;`;

export const DatabaseSetupModal: React.FC<DatabaseSetupModalProps> = ({ isOpen, onClose }) => {
  const [step, setStep] = useState(1);
  const [sqlSteps, setSqlSteps] = useState({ 1: DEFAULT_SQL_1, 2: DEFAULT_SQL_2, 3: DEFAULT_SQL_3, 4: SIMULATION_SQL });
  const [errorInput, setErrorInput] = useState("");
  const [isFixing, setIsFixing] = useState(false);
  const [fixSuccess, setFixSuccess] = useState(false);

  if (!isOpen) return null;

  const currentSql = sqlSteps[step as keyof typeof sqlSteps];

  const handleFixSql = async () => {
      if (!errorInput.trim()) return;
      setIsFixing(true);
      setFixSuccess(false);
      try {
          const fixedSql = await fixSqlScript(currentSql, errorInput);
          setSqlSteps(prev => ({ ...prev, [step]: fixedSql }));
          setFixSuccess(true);
          setErrorInput(""); // Clear error after fix
      } catch (e: any) {
          alert("Fix Failed: " + e.message);
      } finally {
          setIsFixing(false);
      }
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-fade-in font-sans">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-4xl h-[90vh] flex flex-col overflow-hidden relative">
        <div className="bg-gray-900 px-6 py-4 flex justify-between items-center shrink-0 border-b border-gray-800">
          <div className="flex items-center gap-3">
             <div className="p-2 bg-orange-600 rounded-lg shadow-lg shadow-orange-500/30">
                <Database className="w-5 h-5 text-white" />
             </div>
             <div>
                <h3 className="text-lg font-bold text-white flex items-center gap-2">
                    System Installer
                    <span className="text-[10px] bg-red-500 text-white font-black px-2 py-0.5 rounded">V9.0.18 PAYOUT FIX</span>
                </h3>
                <p className="text-xs text-gray-400">Step {step} of 4: {step === 4 ? 'Test Data Seed (Simulation)' : step === 1 ? 'Tables & Settings' : step === 2 ? 'Core Triggers (Dynamic Tiers)' : 'Admin Functions'}</p>
             </div>
          </div>
          <button onClick={onClose} className="text-gray-400 hover:text-white transition-colors"><X className="w-6 h-6"/></button>
        </div>
        
        {/* Step Indicator */}
        <div className="bg-gray-100 p-4 border-b border-gray-200 flex justify-between items-center">
            <div className="flex items-center gap-2">
                {[1, 2, 3, 4].map(num => (
                    <React.Fragment key={num}>
                        <div 
                            onClick={() => setStep(num)} 
                            className={`
                                w-8 h-8 rounded-full flex items-center justify-center text-xs font-bold cursor-pointer transition-all
                                ${step >= num ? 'bg-orange-600 text-white scale-110 shadow-md' : 'bg-gray-300 text-gray-500 hover:bg-gray-400'}
                            `}
                        >
                            {num}
                        </div>
                        {num < 4 && <div className={`h-1 w-8 rounded ${step > num ? 'bg-orange-600' : 'bg-gray-300'}`}></div>}
                    </React.Fragment>
                ))}
            </div>
            
            <div className="text-xs font-bold text-gray-600 flex items-center gap-2">
                {step === 1 && "Create Tables"}
                {step === 2 && "Setup Logic"}
                {step === 3 && "Finalize Permissions"}
                {step === 4 && <span className="text-purple-600 flex items-center gap-1"><TestTube className="w-3 h-3"/> Seed Simulation Data</span>}
            </div>
        </div>
        
        <div className="flex-1 overflow-hidden flex flex-col relative bg-gray-950">
            <div className="absolute top-4 right-4 z-10 flex gap-2">
                <CopyToClipboard text={currentSql} label={`Copy SQL`} className="bg-green-600 hover:bg-green-700 text-white border-none shadow-lg font-bold" />
            </div>
            <pre className="p-6 text-xs font-mono text-green-400 overflow-auto h-full scrollbar-thin scrollbar-thumb-gray-800 scrollbar-track-transparent leading-relaxed selection:bg-green-900 selection:text-white whitespace-pre-wrap break-all">
                {currentSql}
            </pre>
        </div>

        {/* ERROR FEEDBACK SECTION */}
        <div className="bg-red-50 p-4 border-t border-red-100">
            <div className="flex items-center gap-2 mb-2 text-red-700 font-bold text-sm">
                <Bug className="w-4 h-4"/> SQL Execution Error?
            </div>
            <div className="flex gap-3">
                <textarea 
                    value={errorInput}
                    onChange={(e) => { setErrorInput(e.target.value); setFixSuccess(false); }}
                    placeholder="Paste the error message from Supabase SQL Editor here (e.g. 'unterminated dollar-quoted string')..."
                    className="flex-1 p-3 text-xs bg-white border border-red-200 rounded-lg text-gray-700 focus:outline-none focus:ring-2 focus:ring-red-500 font-mono"
                    rows={2}
                />
                <button 
                    onClick={handleFixSql}
                    disabled={isFixing || !errorInput.trim()}
                    className="px-4 bg-red-600 hover:bg-red-700 text-white rounded-lg font-bold text-xs flex flex-col items-center justify-center gap-1 min-w-[100px] disabled:opacity-50 disabled:cursor-not-allowed transition-all shadow-md"
                >
                    {isFixing ? <Loader2 className="w-5 h-5 animate-spin"/> : <Wand2 className="w-5 h-5" />}
                    {isFixing ? "Fixing..." : "Auto-Fix SQL"}
                </button>
            </div>
            {fixSuccess && (
                <div className="mt-2 text-xs text-green-700 font-bold flex items-center gap-1 animate-fade-in">
                    <CheckCircle className="w-3 h-3"/> SQL Repaired & Minified! Please Copy & Run again.
                </div>
            )}
        </div>

        <div className="bg-white p-4 border-t border-gray-200 text-xs text-gray-500 flex justify-between items-center">
             <div className="flex items-center gap-2">
                 <Terminal className="w-4 h-4" />
                 <span><strong>Instructions:</strong> Copy SQL above -> Run in Supabase -> If Error, Paste below & Fix -> Next</span>
             </div>
             
             <div className="flex gap-3">
                 <button 
                    disabled={step === 1}
                    onClick={() => { setStep(s => Math.max(1, s - 1)); setErrorInput(""); setFixSuccess(false); }}
                    className="px-4 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg font-bold disabled:opacity-50"
                 >
                     Back
                 </button>
                 <button 
                    disabled={step === 4}
                    onClick={() => { setStep(s => Math.min(4, s + 1)); setErrorInput(""); setFixSuccess(false); }}
                    className="px-4 py-2 bg-black hover:bg-gray-800 text-white rounded-lg font-bold flex items-center gap-2 disabled:opacity-50"
                 >
                     Next Step <ChevronRight className="w-4 h-4" />
                 </button>
             </div>
        </div>
      </div>
    </div>
  );
};